name: CI

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.4
    - name: Set up JDK 11
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: compile
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        arguments: assemble
    - name: jvmTest
      uses: gradle/actions/setup-gradle@v3.3.2
      with:
        arguments: jvmTest
